default: &default
  url: <%= ENV.fetch('DATABASE_URL', '5432') %>
  adapter: <%= ENV.fetch('DB_ADAPTER') { 'postgresql' } %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: postgres

test:
  <<: *default
  database: postgres_test

production:
  <<: *default
  database: postgres_production
